### ISSUE TITLE
t0 and offset labels swapped with each other

### ISSUE THREAD

**Issue by elizabethnoble0714** [openmicroscopy/Imperial-FLIMfit#124] opened 2015-03-03 18:42 UTC
The t0 and offset labels in the results parameters have been swapped with each other

**Comment by imunro** [comment] 2015-03-03 21:09
Sorry but I'm unsure where exactly this is occurring ?

**Comment by seanwarren** [comment] 2015-03-04 09:04
Duplicate of #123

**Closed by seanwarren** 2015-03-04 09:04 UTC
