### ISSUE TITLE
IRF timing  issues.

### ISSUE THREAD

**Issue by imunro** [openmicroscopy/Imperial-FLIMfit#169] opened 2015-11-26 11:34 UTC
Frederik reports

"FLIMfit is not behaving like it should. If we are loading a Coumarin sample with delays from 0-16000ps and a scatteredIRF with delays from 0-4000ps FLIMfit is just fitting the decay from 4000ps. If we load an IRF with for example 0-6000ps, it is fitting just from 6000ps. See attached image.
If we load an IRF over the full range 0-16000ps FLIMfit is not fitting it properly. It is not recognizing the peak."

![flimfiterrorirf](https://cloud.githubusercontent.com/assets/1183110/11422148/9b80316a-9431-11e5-91b3-34188225b26a.png)

**Comment by imunro** [comment] 2015-11-26 12:25
@f.gorlitz14@imperial.ac.uk   @g.chennell13@csc.mrc.ac.uk   Can I check you guys can see this?
I'm not going to get a chance to look at it now until at least Tue I'm afraid. Sorry.

**Comment by imunro** [comment] 2015-11-26 14:05
@kkwakwa @gchennell @Fredxxx

**Comment by gchennell** [comment] 2015-11-26 14:22
Hi - I have seen this.

**Comment by Fredxxx** [comment] 2015-11-26 14:32
me as well

**Comment by gchennell** [comment] 2015-11-26 15:56
Hi,
I just though to try out an idea. Using the IRF that Fred imaged on 15october I managed to get a much more sensible type of fit. This maybe suggests something about the file rather than the data it holds and what FLIMFit is trying to do. ![used the wrong irf and got a better result loldecay](https://cloud.githubusercontent.com/assets/7990390/11426687/ae047df4-9455-11e5-89a5-3e02e5cb8e96.png)
Not saying this is what I will use, although the lifetime value it fitted was what was expected.

**Comment by imunro** [comment] 2015-11-26 16:34
Thanks Georgre That makes sense as I've never seen behaviour like that before. @Fredxxx could you put the data and irf in question somewhere that we can access (the OMER server would be my choice)

**Comment by seanwarren** [comment] 2015-11-26 23:21
@imunro I think this issue is related to commit 5a924290372d7358132834009cec70c88fcdbdbb . 
I've made a pull request which should address the problem. 

@gchennell @Fredxxx , you should be able to work around this issue by making sure there are no data time points before the first IRF timepoint. FLIMfit should pad automatically for you but it's doing this incorrectly at the moment, leading to this issue. You can manually insert some extra zero time points into the IRF file (making sure the spacing between them is the same as the spacing in the rest of the IRF).

**Comment by imunro** [comment] 2015-11-27 10:55
I've only managed to look quickly at Sean's fix but I think we can go ahead and try - it's all in a beta release anyway. Unfortunately something has broken the builds this morning. So it won't be available for a while. Apologies.

**Comment by imunro** [comment] 2015-11-29 20:01
Sean has now fixed the buld so a version with his fix for this issue is available from https://ci.openmicroscopy.org/view/Consortium/job/FLIMfit-latest-win/OME=5.1,label=vc110/
(Wonder what the point of me is ?)

@Fredxxx @gchennell could you try this and see if it fixes the problem? Thanks.

**Comment by seanwarren** [comment] 2015-11-29 22:13
Just so you're aware this is a potential fix - I don't have an example IRF that reproduces the bug so can't test yet.

**Comment by gchennell** [comment] 2015-12-02 15:09
Hi,

I've now tried to fit using the newer build sent in the link.
Didn't get it to fit properly though. 

Ian, shall I link you to the data in question and see if you can see what is up?
I've got an OMERO account going now so maybe through that? Will it take raw data like this?

![4_9_2_coum6fit_no joy yetdecay](https://cloud.githubusercontent.com/assets/7990390/11534392/6ad5a70a-9906-11e5-8b0a-8e14920feece.png)

Best,
George

**Comment by imunro** [comment] 2015-12-02 15:17
Hi George

Yeah putting the data on there would be good I think.
We can even put it in the public group to give Sean access if needed,

You can import screenshots to OMERO & if you’re working directly from OMERO in FLIMfit you can just r-click
to save the displayed fit  (or images or whatever) back into the OMERO server.

Ian



On 2 Dec 2015, at 15:09, gchennell <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I've now tried to fit using the newer build sent in the link.
Didn't get it to fit properly though.

Ian, shall I link you to the data in question and see if you can see what is up?
I've got an OMERO account going now so maybe through that? Will it take raw data like this?

[4_9_2_coum6fit_no joy yetdecay]<https://cloud.githubusercontent.com/assets/7990390/11534392/6ad5a70a-9906-11e5-8b0a-8e14920feece.png>

Best,
George

**Comment by seanwarren** [comment] 2015-12-02 15:52
George, could you email me the irf you're using please? To my old IC address or s.warren(at)garvan.org.au. Cheers Sean

**Comment by imunro** [comment] 2015-12-02 16:06
George. Can I just confirm? You can't fit this data/irf combination either with the latest build (inc my attempted fix and Sean's fix to my fix) or with older versions?  If so this might imply the issue lies in the data.

**Comment by imunro** [comment] 2015-12-03 12:38
Sean I've put a copy of Georges data in 
https://cisbic.bioinformatics.ic.ac.uk/omero/webclient/?show=dataset-8158
or if you can still vpn you can access it directly at 
https://cisbic.bioinformatics.ic.ac.uk/omero/webclient/?show=dataset-8157

**Comment by gchennell** [comment] 2015-12-03 19:28
Sorry - yes to confirm - older versions also make the same error - just a straight line like the above image

**Comment by seanwarren** [comment] 2015-12-03 21:33
Hi all, looks like the problem is that the IRF data is saved in reverse time order in the TIFFs. FLIMfit loads it in as-is (but requires the IRF to be arranged in equally spaced ascending order). 

I've committed a fix for this, fc91b2ca2a6070dba62e1074c387eca6e9c08d6b. Now it should sort the data on import. I've tested the data provided and it seems to work OK

**Closed by seanwarren** 2015-12-03 21:33 UTC

**Comment by imunro** [comment] 2015-12-03 21:44
Hi I've seen data saved in reverse time order as well. 
Long term I'll modify the loading so that all data gets re-ordered but for now I think we might be better  to fix the OpenFlim acquisition software.

**Comment by seanwarren** [comment] 2015-12-03 22:30
Actually the data itself doesn't really need to be ordered (although it recognises equally spaced ascending data and can process that a bit faster). It's just the IRF so I think the commit above should solve the issue.

**Comment by imunro** [comment] 2015-12-03 22:44
Oh! I didn't know that
