### ISSUE TITLE
Connect to OMERO.server dialog

### ISSUE THREAD

**Issue by pwalczysko** [openmicroscopy/Imperial-FLIMfit#92] opened 2014-09-08 13:42 UTC
FLIMfit 4.7.1 on Windows 7  laptop. 
When connecting to a server with a freshly downloaded FLIMfit (happens EACH time, but the first time the form is not pre-filled), then the first line of the dialog have 
   - strange characters under ``Server`` text. 
   - when Tab key is used to go to the next line of the form on the ``Server`` line, the cursor ends up on the 3rd line, thus jumping over the ``Port`` line
   - nevertheless, the ``Port`` line is compulsory -> you have to manually drive back into the ``Port`` line and fill in the number
   - there is a strange large grey space at the top of the dialog

![screen shot 2014-09-08 at 14 46 21](https://cloud.githubusercontent.com/assets/2478303/4186168/905b3630-375e-11e4-882b-16fe88ca991e.png)

**Comment by imunro** [comment] 2015-03-09 14:40
Addressed Tab order issue in Commit 2d033e3. Unable to reproduce the other issues 
@pwalczysko  Does it help or hinder you if I rebuild with this change for 4.8.0 ?

**Comment by pwalczysko** [comment] 2015-03-09 14:46
@imunro : Please rebuild now.
I do not think that the strange character issue is valid anymore, thanks for fixing the tab.

**Comment by imunro** [comment] 2015-03-09 17:02
Apparently the strange characters are still an issue.

**Comment by imunro** [comment] 2015-03-12 14:59
Finally resolved by https://github.com/openmicroscopy/Imperial-FLIMfit/commit/7ae94157094a298a10f71cea7375da5a6f6c718f

**Closed by imunro** 2015-03-12 14:59 UTC
